### ISSUE TITLE
Unexpected incorrect url

### ISSUE THREAD

**Issue by morpheusthewhite** [Monti03/ChangesInWebPages#5]
The program print on terminal an unexpected exception when the inserted site is incorrect
```bash
Traceback (most recent call last):
  File "gui.py", line 140, in run
    text = read(self._url)
  File "/home/francesco/tmp/-ChangesInWebPages/read_pages.py", line 9, in read
    html = urllib.request.urlopen(url).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 451, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'github.com'
```

**Comment by Monti03** [comment]
solved in 6b50c55818002406905bcc440401a5a70cc311a6
